export const APP_REGISTRY = [
  {
    id: 'settings',
    title: 'Settings',
    icon: '⚙️',
    group: 'System',
    component: 'SettingsApp',
    module: () => import('./SettingsApp'),
    freeAccess: true,
    showOnDesktop: true,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'System preferences, account and appearance settings',
  },
  {
    id: 'sticky_notes',
    title: 'Sticky Notes',
    icon: '📝',
    group: 'System',
    component: 'StickerNotes',
    module: () => import('./StickerNotes'),
    freeAccess: false,
    showOnDesktop: true,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Personal and shared reminder notes',
  },
  {
    id: 'blog_editor',
    title: 'Blog Manager',
    icon: '✍️',
    group: 'Admin',
    component: 'BlogEditorApp',
    module: () => import('./BlogEditorApp'),
    freeAccess: false,
    adminOnly: true,
    showOnDesktop: true,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'GuideLines blog editor and publisher (Admin only)',
  },
  {
    id: 'guidelines',
    title: 'GuideLines',
    icon: '📖',
    group: 'Medical',
    component: 'GuidelinesApp',
    module: () => import('./GuidelinesApp'),
    freeAccess: true,
    showOnDesktop: true,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Clinical guidelines and medical references',
  },
  {
    id: 'file_manager',
    title: 'File Manager',
    icon: '📁',
    group: 'Tools',
    component: 'FileExplorer',
    module: () => import('./FileExplorer'),
    freeAccess: false,
    showOnDesktop: true,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Browse and download shared files',
  },
  {
    id: 'db_editor',
    title: 'DB Editor',
    icon: '🗄️',
    group: 'Tools',
    component: 'DataBankEditor',
    module: () => import('./DataBankEditor'),
    freeAccess: false,
    adminOnly: true,        
    showOnDesktop: false,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Database viewer and editor',
  },
  {
    id: 'graphomap',
    title: 'Grapho MAP 3D',
    icon: '🌐',
    group: 'Research',
    component: 'GraphoMap3D',
    module: () => import('./GraphoMap3D'),
    freeAccess: false,
    showOnDesktop: true,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: '3D conceptual mapping tool',
  },
  {
    id: 'appointments',
    title: 'Appointments',
    icon: '📅',
    group: 'Medical',
    component: 'ConsultationApp',
    module: () => import('./ConsultationApp'),
    freeAccess: false,
    showOnDesktop: true,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Schedule and manage appointments',
  },
  {
    id: 'med_calc',
    title: 'Medical Calc',
    icon: '🧮',
    group: 'Medical',
    component: 'MedCalc',
    module: () => import('./MedCalc'),
    freeAccess: false,
    showOnDesktop: true,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Medical calculators and scoring tools',
  },
  {
    id: 'contacts',
    title: 'Contacts',
    icon: '👤',
    group: 'System',
    component: 'ContactsApp',
    module: () => import('./ContactsApp'),
    freeAccess: true,
    showOnDesktop: true,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Contact information and social links',
  },
  {
    id: 'curriculum',
    title: 'Curriculum Vitae',
    icon: '📋',
    group: 'System',
    component: 'CurriculumViewer',
    module: () => import('./CurriculumViewer'),
    freeAccess: true,
    showOnDesktop: true,
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'View academic curriculum and qualifications',
  },
  {
    id: 'script_viewer',
    title: 'Script Viewer',
    icon: '📜',
    group: 'Tools',
    component: 'ScriptViewer',
    module: () => import('./ScriptViewer'),
    freeAccess: false,
    showOnDesktop: false,
    minPlan: 'complete',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'View and browse bioinformatics scripts',
  },
  {
    id: 'terminal',
    title: 'Terminal',
    icon: '💻',
    group: 'Tools',
    component: 'TerminalApp',
    module: () => import('./TerminalApp'),
    freeAccess: false,
    showOnDesktop: false,
    minPlan: 'basic',
    defaultWidth: 'auto',
    defaultHeight: 'auto',
    description: 'Interactive command-line terminal',
  },
];