// /src/pages/ReportPage.jsx

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Helmet } from 'react-helmet';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, Printer, Loader2, Download, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from "@/components/ui/dialog";
import ThemeToggle from '@/components/ThemeToggle';
import { generateRecommendations } from '@/utils/recommendationEngine'; // generateRecommendations is now async
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/components/ui/use-toast';
import axios from 'axios';

const ReportPage = () => {
  const { id } = useParams(); // Still present, might be used later? For now, using logged-in user data.
  const navigate = useNavigate();
  const { user } = useAuth();
  const { toast } = useToast();

  const [reportData, setReportData] = useState(null);
  const [recommendations, setRecommendations] = useState([]); // Holds text recommendations
  const [keyNutrients, setKeyNutrients] = useState([]); // Holds key nutrients for export
  const [loading, setLoading] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [dataError, setDataError] = useState(null); // Added error state

  // Make fetchReportData async
  const fetchReportData = useCallback(async () => {
    if (!user) {
      navigate('/login');
      return;
    }

    setLoading(true);
    setDataError(null); // Reset error
    setRecommendations([]); // Reset recommendations
    setKeyNutrients([]); // Reset key nutrients
    try {
      const response = await axios.get('/api/questionnaire.php');

      if (response.data) {
        const parsedData = response.data;
        parsedData.healthGoals = Array.isArray(parsedData.healthGoals) ? parsedData.healthGoals : [];
        parsedData.healthConcerns = Array.isArray(parsedData.healthConcerns) ? parsedData.healthConcerns : [];
        setReportData(parsedData);

        // *** ASYNC CALL: Await generateRecommendations ***
        const { recommendations: textRecommendations, keyNutrients: nutrients } = await generateRecommendations(parsedData);
        setRecommendations(textRecommendations || []); // Update state after await
        setKeyNutrients(nutrients || []); // Store keyNutrients in state

      } else {
        toast({
          title: 'No Data Found',
          description: 'Please complete the health assessment questionnaire first.',
          variant: 'destructive'
        });
        navigate('/questionnaire');
      }
    } catch (error) {
      console.error("Failed to fetch report data or generate recommendations:", error);
      setDataError("Could not retrieve data or generate recommendations."); // Set error state
      toast({
        title: 'Error Loading Report',
        description: 'Could not retrieve your assessment data or generate recommendations.',
        variant: 'destructive'
      });
      // Optionally navigate back after a delay or keep the user here with the error message
      // navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  }, [user, navigate, toast]);

  useEffect(() => {
    fetchReportData();
  }, [fetchReportData]);

  // Grouping logic remains the same (synchronous)
  const groupedRecommendations = useMemo(() => {
    if (!recommendations) return {};
    return recommendations.reduce((acc, rec) => {
      const category = rec.category;
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(rec.recommendation);
      return acc;
    }, {});
  }, [recommendations]);

  // Print handler remains the same
  const handlePrint = () => {
    window.print();
  };

  // Export handler now uses keyNutrients from state
  const handleExport = async () => {
    // *** Check state variable ***
    if (loading || dataError || !keyNutrients || keyNutrients.length === 0) {
        toast({
            title: "No Recommendations",
            description: loading ? "Report still loading." : (dataError ? "Cannot export due to data error." : "No key nutrients generated to export."),
            variant: "destructive"
        });
        return;
    }

    setIsExporting(true);
    try {
        // Payload uses state variable
        const exportData = {
            _comment: "This is a NutraGenius recommendations file. Use this file on the NutraShop platform to automatically filter and display products that match your personalized health report. Do not edit this file manually.",
            reportDate: new Date().toISOString().split('T')[0],
            recommendedNutrients: keyNutrients
        };

        const jsonString = JSON.stringify(exportData, null, 2);
        const blob = new Blob([jsonString], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'nutragenius_recommendations.json';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast({ title: "Success", description: "Your recommendation file has been downloaded." });
    } catch (error) {
        console.error("Error exporting recommendations:", error);
        toast({ title: "Error", description: "Could not export your report.", variant: "destructive" });
    } finally {
        setIsExporting(false);
    }
  };


  // BMI calculation remains the same
  const calculateBMI = (data) => {
    if (data && data.height && data.weight) {
      const heightM = parseFloat(data.height) / 100;
      const weightKg = parseFloat(data.weight);
      if (heightM > 0 && weightKg > 0) {
        return (weightKg / (heightM * heightM)).toFixed(1);
      }
    }
    return null;
  };

  // --- RENDER LOGIC ---

  // Loading state display
  if (loading) {
    return (
        <div className="flex justify-center items-center h-screen bg-background">
            <Loader2 className="h-8 w-8 animate-spin" />
            <p className="ml-4">Generating your report...</p>
        </div>
    );
  }

  // Error state display
  if (dataError) {
      return (
          <div className="flex flex-col justify-center items-center h-screen bg-background text-center p-4">
              <h1 className="text-2xl font-bold text-destructive mb-4">Error Loading Report</h1>
              <p className="text-muted-foreground mb-6">{dataError}</p>
              <Button
                  variant="outline"
                  onClick={() => navigate('/dashboard')}
              >
                  <ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
              </Button>
          </div>
      );
  }

  // Calculate BMI only if data is loaded successfully
  const bmi = reportData ? calculateBMI(reportData) : null;

  // Render report content if data exists
  return (
    <>
      <Helmet>
        <title>Nutrigenomic Analysis Report - {reportData?.fullName || 'User'}</title>
        <meta name="description" content="Comprehensive nutrigenomic analysis report with personalized dietary and nutritional recommendations" />
      </Helmet>

      <div className="no-print fixed top-4 left-4 z-50">
        <ThemeToggle />
      </div>

      <div className="min-h-screen bg-background py-8 px-4 print:py-0 print:px-0">
        <div className="max-w-5xl mx-auto">
          {/* Action Buttons */}
          <div className="no-print mb-6 flex flex-wrap gap-4 items-center">
            <Button
              variant="ghost"
              onClick={() => navigate('/dashboard')}
              disabled={isExporting}
            >
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
            </Button>
            <Button
              onClick={handlePrint}
              className="gold-bg"
              disabled={isExporting}
            >
              <Printer className="mr-2 h-4 w-4" /> Print Report
            </Button>
             {/* Export Button with Info Dialog */}
            <div className="flex items-center gap-1">
              <Button
                variant="outline"
                onClick={handleExport}
                disabled={isExporting || keyNutrients.length === 0} // Also disable if no nutrients
              >
                {isExporting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
                {isExporting ? "Exporting..." : "Export Recommendations File"}
              </Button>
              <Dialog>
                <DialogTrigger asChild>
                  <Button variant="ghost" size="icon" className="h-9 w-9">
                    <Info className="h-5 w-5 text-muted-foreground" />
                  </Button>
                </DialogTrigger>
                <DialogContent className="sm:max-w-md bg-card text-card-foreground">
                  <DialogHeader>
                    <DialogTitle>About Exporting Recommendations</DialogTitle>
                    <DialogDescription className="pt-4">
                      This feature downloads a JSON file with your key recommended nutrients.
                      <br /><br />
                      Upload this file to <strong className="gold-accent">NutraShop</strong> to filter supplements matching your profile.
                      <br /><br />
                      Do not edit this file manually.
                    </DialogDescription>
                  </DialogHeader>
                </DialogContent>
              </Dialog>
            </div>
          </div>

          {/* Report Content */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white text-black p-8 sm:p-12 rounded-lg shadow-2xl print:shadow-none font-serif print:p-0 print:bg-transparent"
          >
            {/* Header */}
            <header className="text-center mb-12 border-b-4 border-blue-900 pb-6 print:mb-8 print:pb-4">
              <h1 className="text-3xl sm:text-4xl font-bold text-blue-900 mb-2 tracking-wide print:text-3xl">
                NUTRIGENOMIC ANALYSIS REPORT
              </h1>
              <p className="text-lg text-gray-600 print:text-base">
                Personalized Dietary & Nutritional Recommendations
              </p>
              <p className="text-sm text-gray-500 mt-2 print:text-xs">
                Report Date: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
              </p>
            </header>

            {/* Patient Info */}
            <section className="mb-10 print:mb-6">
              <h2 className="text-xl sm:text-2xl font-bold text-blue-900 mb-4 border-b-2 border-blue-900 pb-2 print:text-xl print:mb-3">
                PATIENT INFORMATION
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3 text-base print:text-sm">
                <p><strong>Patient Name:</strong> {reportData.fullName || 'N/A'}</p>
                <p><strong>Age:</strong> {reportData.age ? `${reportData.age} years` : 'N/A'}</p>
                <p><strong>Gender:</strong> {reportData.gender === 'Other' ? reportData.genderOther : reportData.gender || 'N/A'}</p>
                {bmi && <p><strong>Body Mass Index (BMI):</strong> {bmi} kg/m²</p>}
                <p><strong>Height:</strong> {reportData.height ? `${reportData.height} cm` : 'N/A'}</p>
                <p><strong>Weight:</strong> {reportData.weight ? `${reportData.weight} kg` : 'N/A'}</p>
                {reportData.ethnicity && <p><strong>Ethnicity:</strong> {reportData.ethnicity === 'Other' ? reportData.ethnicityOther : reportData.ethnicity}</p>}
              </div>
            </section>

            {/* Lifestyle */}
            <section className="mb-10 print:mb-6">
              <h2 className="text-xl sm:text-2xl font-bold text-blue-900 mb-4 border-b-2 border-blue-900 pb-2 print:text-xl print:mb-3">
                LIFESTYLE ASSESSMENT
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3 text-base print:text-sm">
                <p><strong>Physical Activity:</strong> {reportData.activityLevel || 'N/A'}</p>
                <p><strong>Sleep Duration:</strong> {reportData.sleepHours ? `${reportData.sleepHours} hours/night` : 'N/A'}</p>
                <p><strong>Stress Level:</strong> {reportData.stressLevel ? `${reportData.stressLevel}/10` : 'N/A'}</p>
                <p><strong>Primary Diet:</strong> {reportData.diet === 'Other' ? reportData.dietOther : reportData.diet || 'N/A'}</p>
                <p><strong>Smoking Status:</strong> {reportData.smokingStatus || 'N/A'}</p>
                <p><strong>Alcohol Consumption:</strong> {reportData.alcoholConsumption || 'N/A'}</p>
              </div>
            </section>

            {/* Health Goals */}
            {reportData.healthGoals && reportData.healthGoals.length > 0 && (
              <section className="mb-10 print:mb-6">
                <h2 className="text-xl sm:text-2xl font-bold text-blue-900 mb-4 border-b-2 border-blue-900 pb-2 print:text-xl print:mb-3">
                  HEALTH GOALS
                </h2>
                <p className="text-base leading-relaxed print:text-sm">
                  Identified health objectives: {reportData.healthGoals.join(', ')}.
                </p>
              </section>
            )}

            <div className="print-page-break" style={{ pageBreakAfter: 'always' }}></div>

            {/* Recommendations */}
            <section className="mb-10 print:mb-6">
              <h2 className="text-xl sm:text-2xl font-bold text-blue-900 mb-6 border-b-2 border-blue-900 pb-2 print:text-xl print:mb-4">
                CLINICAL INTERPRETATION & RECOMMENDATIONS
              </h2>
              {/* Check recommendations state */}
              {recommendations.length > 0 ? (
                <div className="space-y-8 print:space-y-6">
                  {Object.entries(groupedRecommendations).map(([category, recs]) => (
                    <div key={category}>
                      <h3 className="text-lg sm:text-xl font-semibold text-gray-800 mb-4 print:text-lg print:mb-2">{category}</h3>
                      {recs.map((recText, index) => (
                        <div
                          key={index}
                          className="text-base leading-relaxed border-l-4 border-blue-200 pl-4 mb-4 last:mb-0 report-recommendation print:text-sm print:pl-3 print:mb-3"
                          dangerouslySetInnerHTML={{ __html: recText }}
                        />
                      ))}
                    </div>
                  ))}
                </div>
              ) : (
                 <div className="space-y-8 print:space-y-6">
                    <div>
                      <h3 className="text-lg sm:text-xl font-semibold text-gray-800 mb-2 print:text-lg">General Recommendations</h3>
                      <div
                        className="text-base leading-relaxed border-l-4 border-blue-200 pl-4 report-recommendation print:text-sm print:pl-3"
                        dangerouslySetInnerHTML={{ __html: "<p>No specific recommendations were triggered based on the data provided. Maintain a balanced diet, regular activity, and adequate sleep. Consult a healthcare professional for personalized advice.</p>" }}
                       />
                    </div>
                 </div>
              )}
            </section>

            {/* Footer */}
            <footer className="mt-16 pt-8 border-t-2 border-gray-300 print:mt-12 print:pt-6">
              <section className="mb-10 print:mb-6">
                <h2 className="text-lg sm:text-xl font-bold text-blue-900 mb-4 print:text-lg print:mb-2">
                  DISCLAIMER
                </h2>
                <p className="text-xs leading-relaxed text-gray-600 print:text-[10px]">
                  This report is for informational purposes only and not medical advice. Consult qualified healthcare professionals before changing your health regimen. Individual results vary.
                </p>
              </section>
              <div className="flex justify-between items-end mt-16 print:mt-12">
                <div>
                  <p className="text-sm text-gray-600 mb-1 print:text-xs">Report Generated By:</p>
                  <p className="font-semibold text-lg print:text-base">NutraGenius Platform</p>
                </div>
                <div className="text-right">
                  <div className="border-t-2 border-black w-48 sm:w-64 mb-2"></div>
                  <p className="text-sm text-gray-600 print:text-xs">Healthcare Professional Signature</p>
                </div>
              </div>
            </footer>
          </motion.div>
        </div>
      </div>
      {/* Global Styles remain the same */}
      <style jsx global>{`
        .report-recommendation p { margin-bottom: 0.75rem; }
        .report-recommendation strong { font-weight: 600; }
        .report-recommendation ul { list-style-type: disc; margin-left: 1.5rem; margin-top: 0.5rem; margin-bottom: 0.75rem; }
        .report-recommendation li { margin-bottom: 0.25rem; }
        @media print {
            .report-recommendation p { margin-bottom: 0.5rem; }
            .report-recommendation ul { margin-top: 0.25rem; margin-bottom: 0.5rem; margin-left: 1.25rem;}
            .report-recommendation li { margin-bottom: 0.15rem; }
            .no-print { display: none; }
            .print-page-break { page-break-after: always; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
      `}</style>
    </>
  );
};

export default ReportPage;
